Partner news block
adobecom/dx-partners pull request #6
Opened 2024-05-08 15:20 UTC by draganatrajkovic

Added blocks:

- Partner News
- Knowledge Base Overview
(Both displayed in a row in the next link)

Link: https://partner-news-block--dx-partners--adobecom.hlx.page/SPP/drafts/dragana/partner-news?milolibs=spectrum-picker-and-chevron-icon--milo--draganatrajkovic&martech=off

2024-05-27 09:57 UTC, dejanpreradovic commented on eds/deps/PartnerCards.js
> +      const response = await fetch('https://14257-chimera-stage.adobeioruntime.net/api/v1/web/chimera-0.0.1/collection?originSelection=dx-partners&contentTypeTags=&secondSource=&secondaryTags=&collec
@draganalilly021 What's the best way in Milo to make this url configurable per environment? This hard coded one points to chimera stage.

2024-05-27 09:57 UTC, dejanpreradovic commented on eds/scripts/scripts.js
> +  contentRoot: '/SPP/spp-shared',
@draganalilly021 I think Ben mentioned that we should use different path here

2024-05-27 10:08 UTC, Ben-Zahler commented on eds/deps/PartnerCards.js
> +      const response = await fetch('https://14257-chimera-stage.adobeioruntime.net/api/v1/web/chimera-0.0.1/collection?originSelection=dx-partners&contentTypeTags=&secondSource=&secondaryTags=&collec
@dejanpreradovic we have a separate ticket to make this configurable. I'm not sure if there is a clean solution for this in Milo :-/

2024-05-27 10:09 UTC, Ben-Zahler commented on eds/scripts/scripts.js
> +  contentRoot: '/SPP/spp-shared',
@draganatrajkovic what is the purpose of this content root?

2024-05-27 10:15 UTC, draganatrajkovic commented on eds/scripts/scripts.js
> +  contentRoot: '/SPP/spp-shared',
It uses that path to find the placeholder.js.
Will be fixed, thank you. @dejanpreradovic @Ben-Zahler

2024-05-27 10:41 UTC, richardhand-fortedigital commented on eds/blocks/knowledge-base-overview/knowledge-base-overview.js
> +  await deps;
@draganatrajkovic do we need to await the deps again here? Looks like the promises are already awaited above.

2024-05-27 10:44 UTC, zagi25 requested changes

2024-05-27 10:55 UTC, richardhand-fortedigital commented on eds/deps/KnowledgeBaseOverview.js
> +        aria-label="${pageNum}">
is the page number enough for accessibility? it's the same as the text content so doesn't provide any additional info, right? Maybe something more description like "Page 1" would be better?

2024-05-27 11:02 UTC, richardhand-fortedigital commented on eds/deps/KnowledgeBaseOverview.js
> +  get paginationList() {
find this name a little confusing since `get pagination` returns the full list (pagination-pages-list). Perhaps `get paginationPageActions` or similar would work better.

2024-05-27 11:08 UTC, richardhand-fortedigital commented on eds/deps/KnowledgeBaseOverview.js
> +        <button class="pagination-next-btn ${this.paginationCounter === this.totalPages || !this.paginatedCards?.length ? 'disabled': ''}" @click="${this.handleNextPage}" aria-label="${this.blockData
re. accessibility, the aria label is the same as the text content here. Do we need it? Or keep it but make it more descriptive: e.g. `Next page`?

2024-05-27 11:09 UTC, draganatrajkovic commented on eds/blocks/knowledge-base-overview/knowledge-base-overview.js
> +  await deps;
Right, no need for extra await. Thank you

2024-05-27 11:11 UTC, draganatrajkovic commented on eds/blocks/knowledge-base-overview/knowledge-base-overview.js
> +async function declareKnowledgeBaseOverview() {
It is used before when lit was imported there, no need for async anymore. Thank you

2024-05-27 11:38 UTC, Ben-Zahler commented on eds/blocks/knowledge-base-overview/knowledge-base-overview.js
> +import { getLibs, replaceText, getConfig } from '../../scripts/utils.js';
@draganatrajkovic @saragajic11 as just discussed: let's move the lit components that are specific to one block into the blocks folder and also rename the "deps" folder to "components"

2024-05-27 12:38 UTC, richardhand-fortedigital commented on eds/deps/PartnerCards.js
> +class NewsCard extends LitElement {
does it make sense to move the `NewsCard` to its own module?

2024-05-27 13:26 UTC, draganatrajkovic commented on eds/deps/PartnerCards.js
> +class NewsCard extends LitElement {
This function will be used for some other classes (since we will have a few variations of partners cards in the future)

2024-05-27 13:33 UTC, richardhand-fortedigital commented on eds/deps/PartnerNews.js
> +              <span class="filter-footer-results-mobile">${this.cards?.length} Results</span>
results need localizing here

2024-05-27 13:34 UTC, richardhand-fortedigital commented on eds/deps/PartnerNews.js
> +                  <sp-button @click=${(e) => this.toggleFilter(e.target.closest('.filter-wrapper-mobile'))} aria-label="${this.blockData.localizedText['{{apply}}']}">${this.blockData.localizedText['{
I find the apply concept confusing on mobile. Filters are applied instantly on selection, so apply is really just closing the dialog.

2024-05-27 13:37 UTC, richardhand-fortedigital commented on eds/deps/PartnerNews.js
> +              ${this.getDateFilterTags(filter)}
on mobile the filters are quite compact. Could be a bit awkward for a touch user trying to select one of the list items. Is there a definition in spectrum for making them a bit bigger?

<img width="552" alt="Screenshot 2024-05-27 at 15 32 15" src="https://github.com/adobecom/dx-partners/assets/159765468/dc3eb527-f403-4983-87d2-628e755ca29e">

2024-05-27 13:50 UTC, draganatrajkovic commented on eds/deps/KnowledgeBaseOverview.js
> +  get paginationList() {
is paginationNumbers good enough? :)

2024-05-27 13:57 UTC, draganatrajkovic commented on eds/deps/PartnerNews.js
> +                  <sp-button @click=${(e) => this.toggleFilter(e.target.closest('.filter-wrapper-mobile'))} aria-label="${this.blockData.localizedText['{{apply}}']}">${this.blockData.localizedText['{
we used this https://business.adobe.com/customer-success-stories.html regular caas as a reference, so implementation is the same

2024-05-27 13:58 UTC, draganatrajkovic commented on eds/deps/PartnerNews.js
> +              ${this.getDateFilterTags(filter)}
we used this https://business.adobe.com/customer-success-stories.html regular caas as a reference, so implementation is the same :)

2024-05-27 14:00 UTC, draganatrajkovic commented on eds/deps/PartnerNews.js
> +              <span class="filter-footer-results-mobile">${this.cards?.length} Results</span>
Thank you for great comments!

2024-05-27 14:27 UTC, richardhand-fortedigital commented on eds/deps/KnowledgeBaseOverview.js
> +  get paginationList() {
@draganatrajkovic sounds good!

2024-05-29 12:04 UTC, saragajic11 approved these changes

2024-05-29 12:30 UTC, Ben-Zahler approved these changes

2024-05-29 13:18 UTC, zagi25 approved these changes

2024-05-30 08:10 UTC, richardhand-fortedigital approved these changes

2024-05-30 08:11 UTC, merged